"""Composite PFI estimator and Optuna helper."""

import numpy as np

from .flow import FlowModel
from .score import ScoreModel, freeze_dsm_score


class PFI:
    """Composite estimator that fits score first, then flow.

    Parameters
    ----------
    score_estimator : ScoreModel
        Configured score estimator.
    flow_estimator : FlowModel
        Configured flow estimator.
    fit_on_score_samples : bool, default=True
        If ``True``, fit the flow stage on samples generated by the fitted
        score estimator. If ``False``, fit the flow stage directly on ``X``.
    """

    def __init__(
        self,
        score_estimator,
        flow_estimator,
        fit_on_score_samples=True,
    ):
        """Initialize the composite PFI estimator.

        Parameters
        ----------
        score_estimator : ScoreModel
            Score estimator used in the first fitting stage.
        flow_estimator : FlowModel
            Flow estimator used in the second fitting stage.
        fit_on_score_samples : bool, default=True
            If ``True``, fit the flow stage on score-generated samples.
            If ``False``, fit the flow stage directly on the input ``X``.
        """
        self.score_estimator = score_estimator
        self.flow_estimator = flow_estimator
        self.fit_on_score_samples = fit_on_score_samples

    def fit(self, X, y=None):
        """Fit score stage, freeze score, then fit flow stage.

        Parameters
        ----------
        X : ndarray of shape (n_samples, ndim + 1)
            Time-augmented training data.
        y : None, default=None
            Ignored, kept for estimator API compatibility.

        Returns
        -------
        self : PFI
            Fitted composite estimator.
        """
        self.score_estimator.fit(X)

        frozen_score = self.score_estimator.model_
        if self.score_estimator.solver == 'dsm':
            frozen_score = freeze_dsm_score(
                frozen_score,
                noise_lvl=self.score_estimator.noise_lvl_,
            )

        self.flow_estimator.flow.score = frozen_score
        X_flow = self.score_estimator.sample(X) if self.fit_on_score_samples else X
        self.flow_estimator.fit(X_flow)
        return self

    def predict(self, X, stoch=False):
        """Predict flow values using the fitted flow estimator.

        Parameters
        ----------
        X : ndarray of shape (n_samples, ndim + 1)
            Time-augmented input states.
        stoch : bool, default=False
            Forward stochastic flag to the flow estimator.

        Returns
        -------
        pred : ndarray
            Flow predictions returned by ``flow_estimator.predict``.
        """
        return self.flow_estimator.predict(X, stoch=stoch)

    def sample(self, X, Dt, dt=0.01, stoch=False):
        """Sample trajectories with the fitted flow estimator.

        Parameters
        ----------
        X : ndarray of shape (n_samples, ndim + 1)
            Initial states with time in the last column.
        Dt : float
            Simulation horizon.
        dt : float, default=0.01
            Euler time step.
        stoch : bool, default=False
            Forward stochastic flag to the flow estimator.

        Returns
        -------
        samples : ndarray
            Simulated states returned by ``flow_estimator.sample``.
        """
        return self.flow_estimator.sample(X, Dt=Dt, dt=dt, stoch=stoch)

    def score(self, X, y, stoch=False, dt=0.01):
        """Compute flow-stage energy distance.

        Parameters
        ----------
        X : ndarray of shape (n_samples, ndim + 1)
            Source samples with time in the last column.
        y : ndarray of shape (n_samples, ndim + 1)
            Target samples with time in the last column.
        stoch : bool, default=False
            Forward stochastic flag to the flow estimator.
        dt : float, default=0.01
            Integration step passed to the flow estimator.

        Returns
        -------
        scores : ndarray
            Per-time energy distance values from ``flow_estimator.score``.
        """
        return self.flow_estimator.score(X, y, stoch=stoch, dt=dt)


def hyperopt_pfi(
    X,
    fit_on_score_samples=True,
    n_trials=50,
    L=5,
    fac=2,
    nb=1,
    device="cpu",
    seed=0,
    verbose=True,
):
    """Run Optuna multi-objective optimization for the composite PFI estimator.

    Parameters
    ----------
    X : ndarray of shape (n_samples, ndim + 1)
        Time-augmented training data.
    fit_on_score_samples : bool, default=True
        Passed to ``PFI`` constructor.
    n_trials : int, default=50
        Number of Optuna trials.
    L : int, default=5
        Number of DSM noise levels used in score training.
    fac : int, default=2
        Temporal upsampling factor used in flow matching.
    nb : int, default=1
        Number of mini-batches used for OT stitching in flow matching.
    device : str or torch.device, default='cpu'
        Device used by estimators.
    seed : int, default=0
        Seed forwarded to neural network constructors.

    Returns
    -------
    study : optuna.study.Study
        Fitted Optuna study with two objectives:
        ``mean(PFI.score_estimator.score(X))`` and
        mean flow interpolation error from ``t0`` to each later snapshot,
        using only source cells at ``t0``.
    """
    import optuna
    import torch.nn as nn

    from .flow.models import CLEFlow
    from .flow.interpolants import ChebyshevInterpolant
    from .utils.nns import DNN, SpectralNormDNN
    from .score import geometric_sequence

    optuna.logging.set_verbosity(optuna.logging.INFO)
    ndim = X.shape[1] - 1

    def objective(trial):
        snet = trial.suggest_categorical("snet", ["dnn", "spectral"])
        fnet = trial.suggest_categorical("fnet", ["dnn", "spectral"])
        score_cls = DNN if snet == "dnn" else SpectralNormDNN
        flow_cls = DNN if fnet == "dnn" else SpectralNormDNN

        sw = trial.suggest_categorical("sw", [64, 128])
        fw = trial.suggest_categorical("fw", [64, 128])
        sd = trial.suggest_int("sd", 2, 5, step=1)
        fd = trial.suggest_int("fd", 2, 5, step=1)

        min_sigma = np.min(geometric_sequence(L))
        nl = trial.suggest_float("nl", min_sigma, 0.6)
        lx = trial.suggest_float("lx", 0.4, 1.5, step=0.1)

        score_sizes = [ndim + 2] + [sw] * sd + [ndim]
        flow_sizes = [ndim] + [fw] * fd + [ndim]

        score_net = score_cls(score_sizes, activation=nn.ELU(), seed=seed)
        force_net = flow_cls(flow_sizes, activation=nn.ELU(), seed=seed)
        flow_model = CLEFlow(net=force_net, score=None, Ndim=ndim, lx=lx)

        score_estimator = ScoreModel(
            model=score_net,
            solver="dsm",
            solver_kwargs={
                "L": L,
                "n_epochs": 5000,
                "lr": 1e-3,
                "bs": None,
                "adp_flag": 1,
                "verbose": False,
            },
            noise_lvl=nl,
            device=device,
        )
        flow_estimator = FlowModel(
            flow=flow_model,
            growth=None,
            solver="fm",
            solver_kwargs={
                "interp": ChebyshevInterpolant(device=device),
                "nb": nb,
                "fac": fac,
                "n_epochs": 4000,
                "lr": 1e-3,
                "verbose": False
            },
            device=device,
        )
        est = PFI(
            score_estimator=score_estimator,
            flow_estimator=flow_estimator,
            fit_on_score_samples=fit_on_score_samples,
        )
        est.fit(X)

        score_obj = float(np.mean(est.score_estimator.score(X)))
        times = np.sort(np.unique(X[:, -1]))
        X0 = X[np.isclose(X[:, -1], times[0])]
        flow_err = []
        for tk in times[1:]:
            Xk = X[np.isclose(X[:, -1], tk)]
            flow_err.append(est.flow_estimator.score(X0, Xk, stoch=True)[0])
        flow_obj = float(np.mean(flow_err))
        return score_obj, flow_obj

    study = optuna.create_study(
        directions=["minimize", "minimize"],
    )
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
    return study
